### ISSUE TITLE
배포용 branch 필요

### ISSUE THREAD

**Issue by sejin1031** [BS00000001/hu-oss-sw-2019-pbl2#13]
Linux, Mac OS, Window 각각 Branch 생성하여 패키징 된 파일 업로드 하면 될 것 같습니다.

- [ ] Windows
- [ ] Mac OS
- [ ] Linux

**Comment by kwon4450** [comment]
운영체제에 상관없이 프로그램을 빌드하고 실행시킬 수 있는 브랜치를 생성하였습니다.
